---
- name: setup bastion host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: import bastion setup variables
      include_vars: vars/bastion_setup

    - name: import VPC setup Variables
      include_vars: vars/output_vars

    - name: create serhieiev ec2 key
      ec2_key:
        name: ec2-key
        region: "{{region}}"
      register: ec2_key_out

    - name: save private key into file bastion-key.pem
      copy:
        content: "{{ec2_key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: ec2_key_out.changed

    - name: create SG for bastion host
      ec2_group:
        name: bastion-host-SG
        description: only allow SSH access from my IP
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: bastion_SG_out

    - name: create bastion host
      ec2:
        key_name: ec2-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "bastion-host"
          Project: serhieiev
          Owner: DevOps Team
        exact_count: 1
        count_tag:
          Name: "bastion-host"
          Project: serhieiev
          Owner: DevOps Team
        group_id: "{{bastion_SG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out
